<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="52" started-at="2021-03-17T21:15:37 BDT" finished-at="2021-03-17T21:15:37 BDT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="52" started-at="2021-03-17T21:15:37 BDT" finished-at="2021-03-17T21:15:37 BDT">
      <class name="com.SimpleUnit.SimpleUnitTest">
        <test-method status="PASS" signature="testFor0Elements()[pri:0, instance:com.SimpleUnit.SimpleUnitTest@887af79]" name="testFor0Elements" duration-ms="8" started-at="2021-03-17T21:15:37 BDT" finished-at="2021-03-17T21:15:37 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFor0Elements -->
        <test-method status="FAIL" signature="testFor1Elements()[pri:0, instance:com.SimpleUnit.SimpleUnitTest@887af79]" name="testFor1Elements" duration-ms="1" started-at="2021-03-17T21:15:37 BDT" finished-at="2021-03-17T21:15:37 BDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [12] but found [45]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [12] but found [45]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.SimpleUnit.SimpleUnitTest.testFor1Elements(SimpleUnitTest.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFor1Elements -->
        <test-method status="FAIL" signature="testFor2Elements()[pri:0, instance:com.SimpleUnit.SimpleUnitTest@887af79]" name="testFor2Elements" duration-ms="1" started-at="2021-03-17T21:15:37 BDT" finished-at="2021-03-17T21:15:37 BDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [27] but found [28]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [27] but found [28]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.SimpleUnit.SimpleUnitTest.testFor2Elements(SimpleUnitTest.java:56)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFor2Elements -->
        <test-method status="PASS" signature="testFor5Elements()[pri:0, instance:com.SimpleUnit.SimpleUnitTest@887af79]" name="testFor5Elements" duration-ms="1" started-at="2021-03-17T21:15:37 BDT" finished-at="2021-03-17T21:15:37 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFor5Elements -->
        <test-method status="PASS" signature="testFor6Elements()[pri:0, instance:com.SimpleUnit.SimpleUnitTest@887af79]" name="testFor6Elements" duration-ms="1" started-at="2021-03-17T21:15:37 BDT" finished-at="2021-03-17T21:15:37 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFor6Elements -->
      </class> <!-- com.SimpleUnit.SimpleUnitTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
